name: my-gha-action

on: [push]

jobs:
  boot:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: 1.10.1.693
          clj-kondo: 2022.05.31
          cljfmt: 0.10.2

      - name: Run Lint
        run: clj-kondo --lint src

      - name: Run Format Check
        run: cljfmt check